module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert(
      "zproducts",
      [
        {
          id: 1,
          brand_id: 1,
          description: "Modelo de alto rendimiento para competición.",
          model: "RS2025",
          price: 2200,
          image: "image-1759030748535.jpeg",
          sale_id: 1,
          color_id: 3,
          category_id: 2,
          gender_id: 2,
          size_id: 1,
        },
        {
          id: 2,
          brand_id: 2,
          description: "Bicicleta urbana cómoda y ligera para el día a día.",
          model: "CityCruiser",
          price: 950,
          image: "allTerra.jpg",
          sale_id: 1,
          color_id: 2,
          category_id: 1,
          gender_id: 1,
          size_id: 2,
        },
        {
          id: 3,
          brand_id: 3,
          description: "Mountain bike con suspensión total para terrenos difíciles.",
          model: "TrailMaster-X",
          price: 3500,
          image: "skylineV.jpg",
          sale_id: 1,
          color_id: 3,
          category_id: 3,
          gender_id: 2,
          size_id: 3,
        },
        {
          id: 4,
          brand_id: 1,
          description: "Modelo retro con un diseño clásico y elegante.",
          model: "Classic-70",
          price: 1500,
          image: "olmoWish.jpg",
          sale_id: 1,
          color_id: 4,
          category_id: 1,
          gender_id: 1,
          size_id: 1,
        },
        {
          id: 5,
          brand_id: 4,
          description: "Bicicleta de Gravel versátil para asfalto y caminos de tierra.",
          model: "GravelRider",
          price: 2800,
          image: "image-1762182465882.jpeg",
          sale_id: 1,
          color_id: 5,
          category_id: 4,
          gender_id: 2,
          size_id: 2,
        },
        {
          id: 6,
          brand_id: 2,
          description: "Bicicleta eléctrica plegable, perfecta para viajes cortos.",
          model: "E-Fold",
          price: 1850,
          image: "image-1762182350421.jpeg",
          sale_id: 2,
          color_id: 1,
          category_id: 5,
          gender_id: 1,
          size_id: 3,
        },
        {
          id: 7,
          brand_id: 3,
          description: "Bicicleta de carretera aerodinámica para altas velocidades.",
          model: "AeroPro",
          price: 4100,
          image: "image-1762176478858.jpeg",
          sale_id: 1,
          color_id: 2,
          category_id: 2,
          gender_id: 2,
          size_id: 1,
        },
        {
          id: 8,
          brand_id: 4,
          description: "Modelo infantil con ruedas de apoyo y diseño divertido.",
          model: "KidAdventure",
          price: 450,
          image: "image-1762182198231.avif",
          sale_id: 2,
          color_id: 3,
          category_id: 6,
          gender_id: 3, 
          size_id: 4, 
        },
        {
          id: 9,
          brand_id: 1,
          description: "Fat bike para nieve y arena, máxima tracción.",
          model: "SnowBeast",
          price: 1999,
          image: "image-1762176175849.jpeg",
          sale_id: 1,
          color_id: 5,
          category_id: 3,
          gender_id: 1,
          size_id: 2,
        },
        {
          id: 10,
          brand_id: 5, 
          description: "Bicicleta Fixie de piñón fijo para ciclistas avanzados.",
          model: "FixieGear",
          price: 890,
          image: "image-1762176251289.jpeg",
          sale_id: 1,
          color_id: 4,
          category_id: 1,
          gender_id: 2,
          size_id: 3,
        },
        {
          id: 11,
          brand_id: 5,
          description: "Modelo de ciudad con cesta delantera y guardabarros.",
          model: "UrbanChic",
          price: 1100,
          image: "images.png",
          sale_id: 2,
          color_id: 1,
          category_id: 1,
          gender_id: 1,
          size_id: 2,
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("zproducts", null, {});
  },
};